name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-16.04
    container: unityci/editor:ubuntu-2019.4.9f1-android-0.12.0
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - run: chmod +x escape_dll_hell.sh

        - run: ./escape_dll_hell

        - name: Decrypt the license file
          run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf
        
        # Activate unity
        - name: Activate Unity
          run: unity-editor -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0
        
        # Build Windows and OSX
        - name: Build Windows Player
          run: unity-editor -quit -batchmode -nographics -silent-crashes -noUpm -logFile -projectPath . -executeMethod BuildProject.BuildAndroid ./testBuild.apk
       
        - uses: actions/setup-python@v2
          with:
            python-version: '3.6'
        - uses: BSFishy/pip-action@v1
          with:
            packages: |
              yadisk

        - name: Archive Windows Build
          run: python upload.py testBuild.apk